In [ ]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPaQ3HTaH2XX+9r8fGwxIVk",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/RajeshRanaGiet/IML-Lab/blob/main/Experiment-2/Numpy.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "a1 = np.array([1,2,3,4,5,6])\n",
        "print(a1)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kwfw3gjKEZA_",
        "outputId": "9b0bf281-2f43-43f2-fe93-bd6551b5b9a5"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[1 2 3 4 5 6]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "arr=np.array([1,2,3,4,5,6])\n",
        "add=arr+5\n",
        "print(add)\n",
        "mul=arr*5\n",
        "print(mul)\n",
        "exp=arr**2\n",
        "print(exp)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CF79iLS-Hi_E",
        "outputId": "10d601f3-c004-45cc-d2a1-1d2c45055b5a"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "6\n",
            "[ 4 10 18]\n",
            "[ 2.71828183  7.3890561  20.08553692]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "a1 = np.array([1,2,3,4,5,6])\n",
        "print(\"First element is \", a1[0])\n",
        "print(\"Last element is \", a1[-1])\n",
        "print(\"From 2 to 4 element is \", a1[2:5])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "01XIvqUlH9_b",
        "outputId": "105994c5-bdc1-40a5-9797-9ae257b0f4ea"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "First element is  1\n",
            "Last element is  6\n",
            "From 2 to 4 element is  [3 4 5]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np\n",
        "\n",
        "a1 = np.array([[1, 2, 3],[4, 5, 6]])\n",
        "\n",
        "a2 = np.array([[1, 2],[3, 4],[5, 6]])\n",
        "\n",
        "a3 = np.zeros((2, 2))\n",
        "\n",
        "for i in range(2):\n",
        "    for j in range(2):\n",
        "        for k in range(3):\n",
        "            a3[i][j] += a1[i][k] * a2[k][j]\n",
        "\n",
        "print(a3)\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "fZTFd4thJlY7",
        "outputId": "97fbcf3c-ecf5-4dfa-8d8b-4bff0b5ddbf6"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[[22. 28.]\n",
            " [49. 64.]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "a1 = [1,2,3,4,5,6]\n",
        "print('Maximum is', np.max(a1))\n",
        "print(\"Mininmum is\", np.min(a1))\n",
        "print(\"Average maximum is\", np.argmax(a1))\n",
        "print(\"Average minimum is\", np.argmin(a1))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "SV9cqVemLrPA",
        "outputId": "d7237f56-a94f-4db2-d58d-4366e405752c"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Maximum is  6\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "a1 = np.array([1, 2, 3])\n",
        "a2 = np.array([4, 5, 6])\n",
        "print(np.concatenate((a1, a2)))\n",
        "print(np.stack((a1, a2)))\n",
        "print(np.vstack((a1, a2)))\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0kVEdlz9MMsv",
        "outputId": "fe435257-2c42-487f-b899-08be8bdb5fd6"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[1 2 3 4 5 6]\n",
            "[[1 2 3]\n",
            " [4 5 6]]\n",
            "[[1 2 3]\n",
            " [4 5 6]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "a1 = np.array([1, 2, 3])\n",
        "a2 = np.array([4, 5, 6])\n",
        "print(\"Element wise equal\", a1 == a2)\n",
        "print(\"Element wise greater\", a1 > a2)\n",
        "print(\"Element wise less\", a1 < a2)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "8SmXwO76MtFX",
        "outputId": "a96b5129-e6ea-4ace-d21f-a8ffa069181f"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Element wise equal [False False False]\n",
            "Element wise greater [False False False]\n",
            "Element wise less [ True  True  True]\n"
          ]
        }
      ]
    }
  ]
}